name: Generate Snake Contribution Grid

on:
  schedule:
    - cron: "0 */12 * * *"  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg

      - name: Upload the animation
        uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: dist/github-snake.svg
